apiVersion: v1
appVersion: 1.0.0
description: OpenEgiz — an open-source digital twin platform for EGIZ solutions.
keywords:
- openegiz
- digital-twin
- IoT
- iot-platform
name: OpenEgiz
sources:
- https://github.com/openegiz/openegiz
version: 1.0.0
