dependencies:
  - name: ditto
    version: 3.3.7
    repository: "https://raw.githubusercontent.com/openegiz/helm-charts/codex/bootstrap-openegiz-helm-charts"
    condition: ditto.enabled
    tags:
      - ditto
      - essencial
  - name: mongodb
    version: ~13.18.5
    repository: "https://raw.githubusercontent.com/openegiz/helm-charts/codex/bootstrap-openegiz-helm-charts"
    condition: mongodb.enabled
    tags:
      - mongodb
      - essencial
  - name: grafana
    version: ~10.1.2
    repository: "https://raw.githubusercontent.com/openegiz/helm-charts/codex/bootstrap-openegiz-helm-charts"
    condition: grafana.enabled
    tags:
      - grafana
      - essencial
  - name: influxdb2
    version: ~2.1.1
    repository: "https://raw.githubusercontent.com/openegiz/helm-charts/codex/bootstrap-openegiz-helm-charts"
    condition: influxdb2.enabled
    tags:
      - influxdb2
      - essencial
  - name: telegraf
    version: ^1.8.27
    repository: "https://raw.githubusercontent.com/openegiz/helm-charts/codex/bootstrap-openegiz-helm-charts"
    condition: telegraf.enabled
    tags:
      - telegraf
      - essencial
  - name: mosquitto
    version: ~0.3.1
    repository: "https://raw.githubusercontent.com/openegiz/helm-charts/codex/bootstrap-openegiz-helm-charts"
    condition: mosquitto.enabled 
    tags:
      - mosquitto
      - essencial
  - name: hono
    version: ^2.5.5
    repository: "https://raw.githubusercontent.com/openegiz/helm-charts/codex/bootstrap-openegiz-helm-charts"
    condition: hono.enabled
    tags:
      - hono
      - essencial
